### ISSUE TITLE
Travis-CI: run Linux tests on trusty

### ISSUE THREAD

**Issue by zmughal** [project-renard/curie#110]
This has newer packages and will make it so that the tests in #52 actually pass!
- https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
- https://docs.travis-ci.com/user/trusty-ci-environment

From https://docs.travis-ci.com/user/multi-os/:

``` yaml
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
```
